### ISSUE TITLE
Add section with other cool blogs

### ISSUE THREAD

**Issue by marioortizmanero** [marioortizmanero/nullderef.com#14]
* https://0x709394.me/index
* https://fasterthanli.me/

**Comment by marioortizmanero** [comment]
Perhaps I should combine Search, Tags and Archive under a single section?

**Comment by marioortizmanero** [comment]
Hi @ramsayleung! I've finally added a link to your blog in mine, here: http://nullderef.com/about/

I just wanted to let you know that the link to nullderef.com in your site here https://0x709394.me/friend is broken, as it redirects to https://0x709394.me/nullderef.com

**Comment by ramsayleung** [comment]
Emmm, it's awkward, I have fixed that. I like the theme of your blog, it looks clean and cool :)

**Comment by marioortizmanero** [comment]
Thanks! Yours is pretty cool with Rust for the backend, too :)
