### ISSUE TITLE
Update RSpotify logo in the "About" page to the new one

### ISSUE THREAD

**Issue by marioortizmanero** [marioortizmanero/nullderef.com#75]
Depends on https://github.com/ramsayleung/rspotify/issues/323

By the way, @ramsayleung, I've just noticed that you seem to have two blogs:

* https://ramsayleung.github.io/
* https://0x709394.me/

I had featured the second one in my blog, but since the first one seems to be more active I'm not sure which one I should point to. Which one do you prefer?

**Comment by ramsayleung** [comment]
The first one :)

The first one is generated by Hugo and Emacs org-mode, I feel comfortable with these tools. The second one is built on [Rust](https://github.com/ramsayleung/blog), it's my first Rust project, and it takes time to maintain, so I choose to simply switch back to GitHub static page
